#!/bin/bash
# Path Follower 快速启动

echo "========== 启动顺序 =========="
echo ""
echo "1. Bag播放: ros2 bag play your_bag --loop --clock"
echo "2. Driver:  python driver.py  (启动Arduino)"
echo "3. DualMap: ros2 run dualmap runner_ros"
echo "4. 控制器: ros2 launch path_follower position_control_launch.py"
echo "5. RViz:   rviz2 -d src/path_follower/rviz/navigation.rviz"
echo ""
echo "⚠️  注意: DualMap在bag播放完后会自动shutdown"
echo "   需要重启bag (--loop) 和 DualMap"
echo ""
echo "⚠️  DualMap只在点击目标时发布路径一次"
echo "   到达目标后需要重新点击新目标"
echo ""
echo "========== 两种控制器 =========="
echo "路径跟踪:   ros2 launch path_follower trans_vel_launch.py"
echo "位置环控制: ros2 launch path_follower position_control_launch.py"
echo ""
echo "========== 参数调节 =========="
echo "位置环参数在: src/path_follower/launch/position_control_launch.py"
echo "  kp_linear: 0.5    # 增大→靠近更快"
echo "  kp_angular: 2.0   # 增大→转向更快"
echo "  max_linear_vel: 0.3"
echo "  use_sequential_mode: True  # 逐点到达"
echo ""
echo "实时调参: ros2 param set /position_control_node kp_linear 0.8"
echo ""
