#!/bin/bash
# 虚拟路径测试指南

echo "========================================="
echo "  虚拟路径测试 (无需相机)"
echo "========================================="
echo ""
echo "适用场景：相机未标定，小场地测试"
echo ""

echo "========== 测试步骤 =========="
echo ""
echo "1️⃣  启动Arduino Driver:"
echo "    python driver.py"
echo ""
echo "2️⃣  发布虚拟路径 (三选一):"
echo ""
echo "   A. 直线路径 (2米):"
echo "      ros2 run path_follower virtual_path --ros-args -p path_type:=straight -p path_length:=2.0"
echo ""
echo "   B. 正方形路径 (1.5米边长):"
echo "      ros2 run path_follower virtual_path --ros-args -p path_type:=square -p path_length:=1.5"
echo ""
echo "   C. 圆形路径 (半径0.8米):"
echo "      ros2 run path_follower virtual_path --ros-args -p path_type:=circle -p path_length:=0.8"
echo ""
echo "3️⃣  启动position_control:"
echo "    source install/setup.bash"
echo "    ros2 launch path_follower position_control_launch.py"
echo ""
echo "4️⃣  (可选) RViz可视化:"
echo "    rviz2 -d src/path_follower/rviz/navigation.rviz"
echo ""

echo "========== 路径说明 =========="
echo ""
echo "📏 直线路径 (straight):"
echo "   - 从(0,0)直走到(length,0)"
echo "   - 推荐length: 1.0-3.0米"
echo "   - 适合测试直线跟踪"
echo ""
echo "📐 正方形路径 (square):"
echo "   - 四个角: (0,0) → (L,0) → (L,L) → (0,L) → (0,0)"
echo "   - 推荐length: 1.0-2.0米"
echo "   - 适合测试转向"
echo ""
echo "⭕ 圆形路径 (circle):"
echo "   - 圆心在(radius,0)，半径radius"
echo "   - 推荐length(半径): 0.5-1.0米"
echo "   - 适合测试连续转向"
echo ""

echo "========== 检查命令 =========="
echo ""
echo "查看虚拟路径:"
echo "  ros2 topic echo /action_path --once"
echo ""
echo "查看odom:"
echo "  ros2 topic echo /odom"
echo ""
echo "查看cmd_vel:"
echo "  ros2 topic echo /cmd_vel"
echo ""
echo "实时调参:"
echo "  ros2 param set /position_control_node kp_linear 0.6"
echo "  ros2 param set /position_control_node max_linear_vel 0.25"
echo ""

echo "========== 安全提示 =========="
echo ""
echo "⚠️  小场地建议:"
echo "   - 直线: 1.5米"
echo "   - 正方形: 1.0米边长"
echo "   - 圆形: 0.5米半径"
echo ""
echo "⚠️  第一次测试:"
echo "   - 降低速度: max_linear_vel=0.2"
echo "   - 手动准备急停"
echo "   - 确保周围无障碍物"
echo ""
